### ISSUE TITLE
5.1.b2 Media Settings after SAVE

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#405]
After changing the background color and saved, i get this:

![Screenshot](https://user-images.githubusercontent.com/4467158/135649589-e0b5d836-2480-413c-9c7b-25b25218957d.png)

Something is missing at the end. 

and this

```
2021-10-01 16:44:04 - WARNING: Unrecognized color string in /home/**********com/**********.org/oc-includes/osclass/classes/ImageProcessing.php on line no 587 Error Code:2 with context: 
'#0 /home/**********com/**********.org/oc-includes/osclass/classes/ImageProcessing.php(587): ImagickDraw->setfillcolor(\'##000000\')
#1 /home/**********com/**********.org/oc-admin/themes/modern/settings/media.php(420): ImageProcessing::createWatermarkImageFromText(\'**********.org Class...\', \'#000000\')
#2 /home/**********com/**********.org/oc-includes/osclass/helpers/hDefines.php(224): require(\'/home/**********com/...\')
#3 /home/**********com/**********.org/oc-includes/osclass/classes/controller/base/AdminSecBaseModel.php(126): osc_current_admin_theme_path(\'settings/media....\')
#4 /home/**********com/**********.org/oc-includes/osclass/classes/controller/admin/settings/CAdminSettingsMedia.php(55): AdminSecBaseModel->doView(\'settings/media....\')
#5 /home/**********com/**********.org/oc-includes/osclass/classes/controller/admin/CAdminSettings.php(93): CAdminSettingsMedia->doModel()
#6 /home/**********com/**********.org/oc-admin/index.php(91): CAdminSettings->doModel()
#7 {main}'
```

I had opened the same issue again a month or so ago, and thought it was fixed.

**Comment by eurobank** [comment]
The BACKGROUND color is saved with # 

![Screenshot](https://user-images.githubusercontent.com/4467158/135652310-aa0a0926-ecff-4841-99ca-544d941fc085.png)


Editing that and removing the #, restores the page and fix the issue. Apparently you SAVE with an "#" ???

**Comment by eurobank** [comment]
It seems that whatever change you make and save in MEDIA settings (not only the colors), you save with that extra #. And then boom.

**Comment by navjottomer** [comment]
See recent commit

**Comment by eurobank** [comment]
fixed. many thanks.
