### ISSUE TITLE
5.1b2 dev - ERROR: Class 'Category' not found

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#422]
Osclass 5.1b2 dev

A possible issue or a theme issue?

```
2021-10-09 12:47:25 - ERROR: Class 'Category' not found in /home/website.com/oc-includes/osclass/helpers/hCategories.php on line no 123 Error Code:0 with context: 
'#0 /home/website.com/oc-content/themes/osclasswizards/header.php(141): osc_count_categories()
#1 /home/website.com/oc-includes/osclass/helpers/hDefines.php(293): require(\'/home/...\')
#2 /home/website.com/oc-content/themes/osclasswizards/main.php(36): osc_current_web_theme_path(\'header.php\')
#3 /home/website.com/oc-includes/osclass/helpers/hDefines.php(293): require(\'/home/...\')
#4 /home/website.com/oc-includes/osclass/classes/controller/CWebMain.php(73): osc_current_web_theme_path(\'main.php\')
#5 /home/website.com/oc-includes/osclass/classes/controller/CWebMain.php(59): CWebMain->doView(\'main.php\')
#6 /home/website.com/index.php(161): CWebMain->doModel()
#7 {main}'

```

**Comment by navjottomer** [comment]
I didn't get any error like this, and it is saying that Category class is not found which is autoloaded in osclass. 
Step to reproduce is needed till then it's just some random error due to plugin, theme or permissions.
